server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/registration_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 7118
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: supersecreto123 # Usa aquí la misma clave que en AUTH-SERVICE
