server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: 7118

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: supersecreto123 # Usa la misma clave que en auth-service
